<?php
// Call fl_data_structures_activerecordTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
	define('PHPUnit_MAIN_METHOD', 'fl_data_structures_activerecordTest::main');
}

if ( !defined('ABSPATH') ) {
	$abspath = realpath(dirname(__FILE__) . '/../../');
	define('ABSPATH', $abspath . '/');
}

require_once 'PHPUnit/Framework.php';
require_once ABSPATH . 'test/fl/test.php'; // Testing-Environment laden

/**
 * Test class for fl_data_structures_activerecord.
 * Generated by PHPUnit on 2008-09-12 at 22:50:12.
 */
class fl_data_structures_activerecordTest extends PHPUnit_Framework_TestCase {
	protected $object;
	public static function main() {
			require_once 'PHPUnit/TextUI/TestRunner.php';

			$suite  = new PHPUnit_Framework_TestSuite('fl_data_structures_activerecordTest');
			$result = PHPUnit_TextUI_TestRunner::run($suite);
	}
	protected function setUp() {
		$factory = new fl_factory();
		$factory->set_data_access(fl_registry::getInstance()->get('data_access'));

		$this->object = $factory->get_ar_class(
			'account/account', // Klassenname
			1,  // Databank-ID
			array('username'=>'tester') // Daten
		);
	}
	protected function tearDown() {
	}

	/**
	 * @todo Implement testSet_data().
	 */
	public function testSet_data() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testGet_data().
	 */
	public function testGet_data() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testGet_data_as_array().
	 */
	public function testGet_data_as_array() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testSay().
	 */
	public function testSay() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testGet().
	 */
	public function testGet() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testSet().
	 */
	public function testSet() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testIs_set().
	 */
	public function testIs_set() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testRemove().
	 */
	public function testRemove() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testLoad().
	 */
	public function testLoad() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testSave().
	 */
	public function testSave() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testDelete().
	 */
	public function testDelete() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement test__toString().
	 */
	public function test__toString() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}

	/**
	 * @todo Implement testValidate_data().
	 */
	public function testValidate_data() {
			// Remove the following lines when you implement this test.
			$this->markTestIncomplete(
				'This test has not been implemented yet.'
			);
	}
}

// Call fl_data_structures_activerecordTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'fl_data_structures_activerecordTest::main') {
	fl_data_structures_activerecordTest::main();
}
?>
