<?php
// Call fl_data_accessTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'fl_data_accessTest::main');
}

if ( !defined('ABSPATH') ) {
	$abspath = realpath(dirname(__FILE__) . '/../../');
	define('ABSPATH', $abspath . '/');
}

require_once 'PHPUnit/Framework.php';
require_once ABSPATH . 'test/fl/test.php';

/**
 * Test class for fl_data_access.
 * Generated by PHPUnit on 2008-09-22 at 03:22:51.
 */
class fl_data_accessTest extends PHPUnit_Framework_TestCase {
	protected $object;
	public static function main() {
		require_once 'PHPUnit/TextUI/TestRunner.php';

		$suite  = new PHPUnit_Framework_TestSuite('fl_data_accessTest');
		$result = PHPUnit_TextUI_TestRunner::run($suite);
	}
	protected function setUp() {
		$this->object = new fl_data_access(array('type'=>null));
	}
	protected function tearDown() {
	}

	public function testGet_data_source() {
		$result = $this->object->get_data_source();
		$this->assertType('data_access', $result);
	}
}

// Call fl_data_accessTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'fl_data_accessTest::main') {
    fl_data_accessTest::main();
}
?>
